### ISSUE TITLE
Installed Firmware on Archer C60 V2; not able to access openwrt

### ISSUE THREAD

**Issue by army-mehak** [xieyaxiongfly/Atheros_CSI_tool_OpenWRT_src#30]
I flashed the router Archer C60 v2 firmware using the web browser. After the update, I wasn't able to connect it through using http://192.168.1.1. So through "PUTTY", I established an SSH connection on 192.168.1.1, where Im trying to download "opkg update" and "opkg install luci".
I have received an error on Putty "opkg download error; failed to establish connection". Any suggestion?

**Comment by kr689** [comment]
How did you manage to resolve thist? I also installed the firmware in TL-WDR4300 v1. After what seemed to b a successful flash, I cannot seem to access 192.168.1.1.

**Comment by Geosearchef** [comment]
Did you use an image containing LUCI? Can you ping the device? Can you ssh into the device?

In case you flashed an image without LUCI, you may be able to install LUCI via ssh opkg or flash a new image via ssh sysupgrade.

Alternatively, if you can't access the device, you can try flashing the image using the bootloader TFTP backup method (https://community.tp-link.com/en/home/forum/topic/81462).

You can find my custom OpenWRT builds with LUCI here: (including the WDR4300)
https://github.com/putterer/csi-auxiliary/tree/main/firmware

Use them at your own risk though!!! They work with the  CSI tool but may still contain some debug statements in the kernel code I modified that may spam your system log for every packet.

**Comment by kr689** [comment]
I found that I have a snapshot version as I am able to ssh into the device. So when trying to install LUCI it can't seem to access the internet. I'm not sure how I go about installing LUCI if that is the case. I'm assuming the computer can only connect to either the router or the internet at one time which is causing this. 

![image](https://user-images.githubusercontent.com/68014287/213167963-cdfe7747-ed31-49fd-ab66-a62b1bc5bc28.png)

Also, I tried to flash the pre-compiled image provided but there was some sort of error when I tried the upgrade. So then I used the image that I compiled using the given source code. I was expecting that it would already have the LUCI installed.

I'm reluctant about doing another flash using the sysupgrade image as I already did one on another one of the same routers and that router seems to be bricked. Since the flash was successful, I don't want to risk bricking this router too.
I'm going to use the TFTP method on that other router to try to recover it but I'm unsure if that will work because the ethernet connection is not being made. Its being detected, but the connection is not being made.

That said the lights on the router don't appear to indicate that it's bricked. But the fact that I cannot connect to it at all means I don't really know how to fix it.

**Comment by kr689** [comment]
Update : So following this: https://openwrt.org/docs/guide-quick-start/ssh_connect_to_the_internet_and_install_luci#:~:text=Connect%20the%20PC%20to%20the,be%20able%20to%20install%20LuCI.

I was able to connect to the internet and was able to ssh into the device using the new IP configured. 
I now have a new problem when I try to install luci:
![image](https://user-images.githubusercontent.com/68014287/213180716-3a2beb5c-7933-4cf4-b8f7-9451e446b955.png)
Any ideas what the issue is now and how I can get around that?

**Comment by Geosearchef** [comment]
About getting the software, as you figured out, you need to connect the router to the internet first using the method you linked.

Alternatively, you can also download the software you need from an openwrt web page after selecting the correct architecture and copy the package file to the router using SFTP, and then install via opkg from file.

About the bricked router, are you sure you used the right (factory VS sysupgrade) image for the right device?
You could try to figure out the routers IP addr using Wireshark.

About recovering, a functional ethernet connection during operation doesn't matter. The bootloader will create a short connection during boot and immediately close that again. You should be able to see that connection attempt to your TFTP server using Wireshark.
Usually this then allows you to recover the device, as the bootloader is unaffected by you flashing a new image.

About installing LUCI, there seems to be a dependency conflict. Maybe you're using an old version of the packet? Did you update the package indices? You can also try manually getting the package and copying+installing from file.
Maybe also ask on an openwrt forum, they know more about this than here.

**Comment by kr689** [comment]
So I had a relatively new version of OpenWrt running on the router and wanted to go to the precompiled CSI tool available version. I used the sysupgrade.bin file. The image check failed but I went ahead and forced the upgrade because it said that if downgrading or going to vendor firmware, the image check will fail and you will need to force the upgrade. it didn't work though I guess.

Right, that is good news. I've gone through the process using SolarWinds so I'll try that again.

Yes, that's where I'll head. 

Cheers for the help. I'll comment in how I solve this.
